/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.joda.time.LocalTime;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        LocalTime currentTime = new LocalTime();
        System.out.println("The time is " + currentTime);
    }
}
